version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: backend
    command: ./wait-for-it.sh mysql-db:3306 -- sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 BlackWhiteChef.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일 마운트
      - ./frontend/dist:/code/frontend/dist          # 프론트엔드 빌드 파일 경로 마운트
      - ./staticfiles:/code/staticfiles              # 정적 파일 경로 마운트
      - ./mediafiles:/code/mediafiles                # 미디어 파일 경로 마운트
    environment:
      SERVER_NAME: ${DJANGO_ALLOWED_HOSTS}  # 환경 변수 설정
    depends_on:
      - web
    command: /bin/sh -c "nginx -g 'daemon off;'"
