global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['backend:8000']  # Django Gunicorn의 메트릭 수집
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]